# Generated by Django 4.1.7 on 2023-04-05 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "conferenceCode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("conferenceName", models.CharField(max_length=20)),
                ("conferenceStartDate", models.DateField(default="2023-06-11")),
                ("conferenceEndDate", models.DateField(default="2023-06-16")),
                ("conferenceLocation", models.CharField(max_length=20)),
                ("conferenceType", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "eventCode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("eventTheme", models.CharField(max_length=20)),
                ("eventTime", models.TimeField()),
                ("keynoteSpeaker", models.CharField(max_length=20)),
                ("eventRoom", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("userCategory", models.CharField(max_length=20)),
                ("userCountry", models.CharField(max_length=20)),
                (
                    "conferenceCode",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.conference",
                    ),
                ),
            ],
        ),
    ]
