# Generated by Django 4.1.7 on 2023-04-27 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conference",
            fields=[
                (
                    "conferenceCode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "conferenceName",
                    models.CharField(default="adminConference", max_length=20),
                ),
                ("conferenceStartDate", models.DateField(default="2023-06-11")),
                ("conferenceEndDate", models.DateField(default="2023-06-16")),
                (
                    "conferenceLocation",
                    models.CharField(default="adminLocation", max_length=30),
                ),
                (
                    "conferenceType",
                    models.CharField(default="adminType", max_length=20),
                ),
                ("agenda", models.FileField(upload_to="agenda/")),
                ("proceedings", models.FileField(upload_to="proceedings/")),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("userCategory", models.CharField(max_length=20)),
                ("userCountry", models.CharField(max_length=20)),
                ("userUniversity", models.CharField(max_length=40)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.conference",
                    ),
                ),
            ],
            options={"verbose_name_plural": "UserProfiles",},
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "eventCode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("eventTheme", models.CharField(max_length=20)),
                ("eventStartTime", models.DateTimeField()),
                ("eventEndTime", models.DateTimeField()),
                ("keynoteSpeaker", models.CharField(max_length=20)),
                ("eventRoom", models.CharField(max_length=20)),
                (
                    "conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.conference",
                    ),
                ),
            ],
        ),
    ]
