# Generated by Django 4.1.7 on 2023-05-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='trackName',
            field=models.CharField(max_length=100),
        ),
    ]
