# Generated by Django 4.1 on 2023-06-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conferenceCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventRoom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventTheme',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='keynoteSpeaker',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='paper',
            name='paperID',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='trackCode',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userCategory',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userCountry',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='userUniversity',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
