# Generated by Django 4.1.7 on 2023-04-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="conferenceLocation",
            field=models.CharField(default="adminLocation", max_length=30),
        ),
    ]
