# Generated by Django 4.1.7 on 2023-04-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="conferenceLocation",
            field=models.CharField(default="adminLocation", max_length=20),
        ),
        migrations.AlterField(
            model_name="conference",
            name="conferenceName",
            field=models.CharField(default="adminConference", max_length=20),
        ),
        migrations.AlterField(
            model_name="conference",
            name="conferenceType",
            field=models.CharField(default="adminType", max_length=20),
        ),
    ]
