# Generated by Django 4.1.7 on 2023-03-27 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="user", new_name="username",
        ),
    ]
