# Generated by Django 4.1.7 on 2023-04-06 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conference",
            name="agendaURL",
            field=models.CharField(
                default="../static/upload/<django.db.models.fields.CharField>/.pdf",
                max_length=100,
            ),
        ),
    ]
