# Generated by Django 4.1.7 on 2023-03-27 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_rename_user_userprofile_username"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="username", new_name="user",
        ),
    ]
