# Generated by Django 4.1.7 on 2023-04-06 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_conference_agendaurl"),
    ]

    operations = [
        migrations.AlterField(
            model_name="conference",
            name="agendaURL",
            field=models.URLField(
                default="../static/upload/<django.db.models.fields.CharField>/.pdf"
            ),
        ),
    ]
