# Generated by Django 4.1.7 on 2023-05-09 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_conference_conferencename_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="conference", name="conferenceType",),
        migrations.RemoveField(model_name="conference", name="proceedings",),
        migrations.RemoveField(model_name="conference", name="program",),
        migrations.RemoveField(model_name="userprofile", name="conference",),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "trackCode",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("trackName", models.CharField(max_length=30)),
                ("proceedings", models.FileField(upload_to="proceedings/")),
                ("program", models.FileField(upload_to="program/")),
                (
                    "Conference",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.conference",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="userprofile",
            name="tracks",
            field=models.ManyToManyField(to="authentication.track"),
        ),
    ]
