# Generated by Django 4.1 on 2023-06-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_conference_conferencecode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='keynoteSpeaker',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
