# Generated by Django 4.1.7 on 2023-05-14 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0003_remove_conference_conferencetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='tracks',
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('ticket_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('checkin', models.BooleanField(default=False)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Tickets',
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tickets',
            field=models.ManyToManyField(to='authentication.ticket'),
        ),
    ]
