# Generated by Django 4.1.7 on 2023-03-27 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_rename_username_userprofile_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="confereceCode",
            new_name="conferenceCode",
        ),
    ]
