# Generated by Django 4.1.7 on 2023-05-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userprofile_tracks_ticket_userprofile_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
    ]
