# Generated by Django 4.1.7 on 2023-05-14 05:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_ticket_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_activated',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(default=uuid.uuid4, max_length=40, primary_key=True, serialize=False),
        ),
    ]
